"""second migration

Revision ID: 69537d5d57ad
Revises: 6e7109d22752
Create Date: 2025-09-28 17:09:37.617511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69537d5d57ad'
down_revision = '6e7109d22752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
